# Generated by Django 5.2.1 on 2025-05-27 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskpilot', '0002_rename_time_reminder_remind_at_reminder_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
